services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    command:
      - sh
      - -c
      - |
        cd /app/ &&
        php artisan migrate &&
        php artisan key:generate &&
        php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - '3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u laravel --password=password"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  dbdata:
