services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/app
    command:
      - sh
      - -c
      - |
        cd /app/ &&
        php artisan key:generate &&
        php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
